
# This file is automatically generated by puppet-swagger-generator and
# any manual changes are likely to be clobbered when the files
# are regenerated.

require_relative '../../../puppet_x/puppetlabs/kubernetes/provider'

Puppet::Type.type(:kubernetes_resource_field_selector).provide(:swagger, :parent => PuppetX::Puppetlabs::Kubernetes::Provider) do

  mk_resource_methods

  def self.instance_to_hash(instance)
    {
    ensure: :present,
    name: instance.metadata.name,
    
      
        
        container_name: instance.containerName.respond_to?(:to_hash) ? instance.containerName.to_hash : instance.containerName,
        
      
    
      
        
        resource: instance.resource.respond_to?(:to_hash) ? instance.resource.to_hash : instance.resource,
        
      
    
      
        
        divisor: instance.divisor.respond_to?(:to_hash) ? instance.divisor.to_hash : instance.divisor,
        
      
    
    object: instance,
    }
  end

  def create
    Puppet.info("Creating kubernetes_resource_field_selector #{name}")
    create_instance_of('resource_field_selector', name, build_params)
  end

  def flush
   unless @property_hash.empty?
     unless resource[:ensure] == :absent
        flush_instance_of('resource_field_selector', name, @property_hash[:object], build_params)
      end
    end
  end

  def destroy
    Puppet.info("Deleting kubernetes_resource_field_selector #{name}")
    destroy_instance_of('resource_field_selector', name)
    @property_hash[:ensure] = :absent
  end

  private
  def self.list_instances
    list_instances_of('resource_field_selector')
  end

  def build_params
    params = {
    
      
        containerName: resource[:container_name],
      
    
      
        resource: resource[:resource],
      
    
      
        divisor: resource[:divisor],
      
    
    }
    params.delete_if { |key, value| value.nil? }
    params
  end
end
