
# This file is automatically generated by puppet-swagger-generator and
# any manual changes are likely to be clobbered when the files
# are regenerated.

require_relative '../../../puppet_x/puppetlabs/kubernetes/provider'

Puppet::Type.type(:kubernetes_ingress_backend).provide(:swagger, :parent => PuppetX::Puppetlabs::Kubernetes::Provider) do

  mk_resource_methods

  def self.instance_to_hash(instance)
    {
    ensure: :present,
    name: instance.metadata.name,
    
      
        service_name: instance.serviceName.respond_to?(:to_hash) ? instance.serviceName.to_hash : instance.serviceName,
      
    
      
        service_port: instance.servicePort.respond_to?(:to_hash) ? instance.servicePort.to_hash : instance.servicePort,
      
    
    object: instance,
    }
  end

  def create
    Puppet.info("Creating kubernetes_ingress_backend #{name}")
    create_instance_of('ingress_backend', name, build_params)
  end

  def flush
   unless @property_hash.empty?
     unless resource[:ensure] == :absent
        flush_instance_of('ingress_backend', name, @property_hash[:object], build_params)
      end
    end
  end

  def destroy
    Puppet.info("Deleting kubernetes_ingress_backend #{name}")
    destroy_instance_of('ingress_backend', name)
    @property_hash[:ensure] = :absent
  end

  private
  def self.list_instances
    list_instances_of('ingress_backend')
  end

  def build_params
    params = {
    
      
        serviceName: resource[:service_name],
      
    
      
        servicePort: resource[:service_port],
      
    
    }
    params.delete_if { |key, value| value.nil? }
    params
  end
end
