
# This file is automatically generated by puppet-swagger-generator and
# any manual changes are likely to be clobbered when the files
# are regenerated.

require_relative '../../../puppet_x/puppetlabs/kubernetes/provider'

Puppet::Type.type(:kubernetes_initializers).provide(:swagger, :parent => PuppetX::Puppetlabs::Kubernetes::Provider) do

  mk_resource_methods

  def self.instance_to_hash(instance)
    {
    ensure: :present,
    name: instance.metadata.name,
    
      
        pending: instance.pending.respond_to?(:to_hash) ? instance.pending.to_hash : instance.pending,
      
    
      
        result: instance.result.respond_to?(:to_hash) ? instance.result.to_hash : instance.result,
      
    
    object: instance,
    }
  end

  def create
    Puppet.info("Creating kubernetes_initializers #{name}")
    create_instance_of('initializers', name, build_params)
  end

  def flush
   unless @property_hash.empty?
     unless resource[:ensure] == :absent
        flush_instance_of('initializers', name, @property_hash[:object], build_params)
      end
    end
  end

  def destroy
    Puppet.info("Deleting kubernetes_initializers #{name}")
    destroy_instance_of('initializers', name)
    @property_hash[:ensure] = :absent
  end

  private
  def self.list_instances
    list_instances_of('initializers')
  end

  def build_params
    params = {
    
      
        pending: resource[:pending],
      
    
      
        result: resource[:result],
      
    
    }
    params.delete_if { |key, value| value.nil? }
    params
  end
end
