
# This file is automatically generated by puppet-swagger-generator and
# any manual changes are likely to be clobbered when the files
# are regenerated.

require_relative '../../../puppet_x/puppetlabs/kubernetes/provider'

Puppet::Type.type(:kubernetes_ingress_rule).provide(:swagger, :parent => PuppetX::Puppetlabs::Kubernetes::Provider) do

  mk_resource_methods

  def self.instance_to_hash(instance)
    {
    ensure: :present,
    name: instance.metadata.name,
    
      
        host: instance.host.respond_to?(:to_hash) ? instance.host.to_hash : instance.host,
      
    
      
        http: instance.http.respond_to?(:to_hash) ? instance.http.to_hash : instance.http,
      
    
    object: instance,
    }
  end

  def create
    Puppet.info("Creating kubernetes_ingress_rule #{name}")
    create_instance_of('ingress_rule', name, build_params)
  end

  def flush
   unless @property_hash.empty?
     unless resource[:ensure] == :absent
        flush_instance_of('ingress_rule', name, @property_hash[:object], build_params)
      end
    end
  end

  def destroy
    Puppet.info("Deleting kubernetes_ingress_rule #{name}")
    destroy_instance_of('ingress_rule', name)
    @property_hash[:ensure] = :absent
  end

  private
  def self.list_instances
    list_instances_of('ingress_rule')
  end

  def build_params
    params = {
    
      
        host: resource[:host],
      
    
      
        http: resource[:http],
      
    
    }
    params.delete_if { |key, value| value.nil? }
    params
  end
end
