
# This file is automatically generated by puppet-swagger-generator and
# any manual changes are likely to be clobbered when the files
# are regenerated.

require_relative '../../../puppet_x/puppetlabs/kubernetes/provider'

Puppet::Type.type(:kubernetes_taint).provide(:swagger, :parent => PuppetX::Puppetlabs::Kubernetes::Provider) do

  mk_resource_methods

  def self.instance_to_hash(instance)
    {
    ensure: :present,
    name: instance.metadata.name,
    
      
        key: instance.key.respond_to?(:to_hash) ? instance.key.to_hash : instance.key,
      
    
      
        value: instance.value.respond_to?(:to_hash) ? instance.value.to_hash : instance.value,
      
    
      
        effect: instance.effect.respond_to?(:to_hash) ? instance.effect.to_hash : instance.effect,
      
    
      
        time_added: instance.timeAdded.respond_to?(:to_hash) ? instance.timeAdded.to_hash : instance.timeAdded,
      
    
    object: instance,
    }
  end

  def create
    Puppet.info("Creating kubernetes_taint #{name}")
    create_instance_of('taint', name, build_params)
  end

  def flush
   unless @property_hash.empty?
     unless resource[:ensure] == :absent
        flush_instance_of('taint', name, @property_hash[:object], build_params)
      end
    end
  end

  def destroy
    Puppet.info("Deleting kubernetes_taint #{name}")
    destroy_instance_of('taint', name)
    @property_hash[:ensure] = :absent
  end

  private
  def self.list_instances
    list_instances_of('taint')
  end

  def build_params
    params = {
    
      
        key: resource[:key],
      
    
      
        value: resource[:value],
      
    
      
        effect: resource[:effect],
      
    
      
        timeAdded: resource[:time_added],
      
    
    }
    params.delete_if { |key, value| value.nil? }
    params
  end
end
