
# This file is automatically generated by puppet-swagger-generator and
# any manual changes are likely to be clobbered when the files
# are regenerated.

require_relative '../../../puppet_x/puppetlabs/kubernetes/provider'

Puppet::Type.type(:kubernetes_deployment_spec).provide(:swagger, :parent => PuppetX::Puppetlabs::Kubernetes::Provider) do

  mk_resource_methods

  def self.instance_to_hash(instance)
    {
    ensure: :present,
    name: instance.metadata.name,
    
      
        
        replicas: instance.replicas.respond_to?(:to_hash) ? instance.replicas.to_hash : instance.replicas,
        
      
    
      
        
        selector: instance.selector.respond_to?(:to_hash) ? instance.selector.to_hash : instance.selector,
        
      
    
      
        
        template: instance.template.respond_to?(:to_hash) ? instance.template.to_hash : instance.template,
        
      
    
      
        
        strategy: instance.strategy.respond_to?(:to_hash) ? instance.strategy.to_hash : instance.strategy,
        
      
    
      
        
        min_ready_seconds: instance.minReadySeconds.respond_to?(:to_hash) ? instance.minReadySeconds.to_hash : instance.minReadySeconds,
        
      
    
      
        
        revision_history_limit: instance.revisionHistoryLimit.respond_to?(:to_hash) ? instance.revisionHistoryLimit.to_hash : instance.revisionHistoryLimit,
        
      
    
      
        
        paused: instance.paused.respond_to?(:to_hash) ? instance.paused.to_hash : instance.paused,
        
      
    
      
        
        rollback_to: instance.rollbackTo.respond_to?(:to_hash) ? instance.rollbackTo.to_hash : instance.rollbackTo,
        
      
    
      
        
        progress_deadline_seconds: instance.progressDeadlineSeconds.respond_to?(:to_hash) ? instance.progressDeadlineSeconds.to_hash : instance.progressDeadlineSeconds,
        
      
    
    object: instance,
    }
  end

  def create
    Puppet.info("Creating kubernetes_deployment_spec #{name}")
    create_instance_of('deployment_spec', name, build_params)
  end

  def flush
   unless @property_hash.empty?
     unless resource[:ensure] == :absent
        flush_instance_of('deployment_spec', name, @property_hash[:object], build_params)
      end
    end
  end

  def destroy
    Puppet.info("Deleting kubernetes_deployment_spec #{name}")
    destroy_instance_of('deployment_spec', name)
    @property_hash[:ensure] = :absent
  end

  private
  def self.list_instances
    list_instances_of('deployment_spec')
  end

  def build_params
    params = {
    
      
        replicas: resource[:replicas],
      
    
      
        selector: resource[:selector],
      
    
      
        template: resource[:template],
      
    
      
        strategy: resource[:strategy],
      
    
      
        minReadySeconds: resource[:min_ready_seconds],
      
    
      
        revisionHistoryLimit: resource[:revision_history_limit],
      
    
      
        paused: resource[:paused],
      
    
      
        rollbackTo: resource[:rollback_to],
      
    
      
        progressDeadlineSeconds: resource[:progress_deadline_seconds],
      
    
    }
    params.delete_if { |key, value| value.nil? }
    params
  end
end
