
# This file is automatically generated by puppet-swagger-generator and
# any manual changes are likely to be clobbered when the files
# are regenerated.

require_relative '../../../puppet_x/puppetlabs/kubernetes/provider'

Puppet::Type.type(:kubernetes_host_alias).provide(:swagger, :parent => PuppetX::Puppetlabs::Kubernetes::Provider) do

  mk_resource_methods

  def self.instance_to_hash(instance)
    {
    ensure: :present,
    name: instance.metadata.name,
    
      
        ip: instance.ip.respond_to?(:to_hash) ? instance.ip.to_hash : instance.ip,
      
    
      
        hostnames: instance.hostnames.respond_to?(:to_hash) ? instance.hostnames.to_hash : instance.hostnames,
      
    
    object: instance,
    }
  end

  def create
    Puppet.info("Creating kubernetes_host_alias #{name}")
    create_instance_of('host_alias', name, build_params)
  end

  def flush
   unless @property_hash.empty?
     unless resource[:ensure] == :absent
        flush_instance_of('host_alias', name, @property_hash[:object], build_params)
      end
    end
  end

  def destroy
    Puppet.info("Deleting kubernetes_host_alias #{name}")
    destroy_instance_of('host_alias', name)
    @property_hash[:ensure] = :absent
  end

  private
  def self.list_instances
    list_instances_of('host_alias')
  end

  def build_params
    params = {
    
      
        ip: resource[:ip],
      
    
      
        hostnames: resource[:hostnames],
      
    
    }
    params.delete_if { |key, value| value.nil? }
    params
  end
end
