
# This file is automatically generated by puppet-swagger-generator and
# any manual changes are likely to be clobbered when the files
# are regenerated.

require_relative '../../../puppet_x/puppetlabs/kubernetes/provider'

Puppet::Type.type(:kubernetes_affinity).provide(:swagger, :parent => PuppetX::Puppetlabs::Kubernetes::Provider) do

  mk_resource_methods

  def self.instance_to_hash(instance)
    {
    ensure: :present,
    name: instance.metadata.name,
    
      
        node_affinity: instance.nodeAffinity.respond_to?(:to_hash) ? instance.nodeAffinity.to_hash : instance.nodeAffinity,
      
    
      
        pod_affinity: instance.podAffinity.respond_to?(:to_hash) ? instance.podAffinity.to_hash : instance.podAffinity,
      
    
      
        pod_anti_affinity: instance.podAntiAffinity.respond_to?(:to_hash) ? instance.podAntiAffinity.to_hash : instance.podAntiAffinity,
      
    
    object: instance,
    }
  end

  def create
    Puppet.info("Creating kubernetes_affinity #{name}")
    create_instance_of('affinity', name, build_params)
  end

  def flush
   unless @property_hash.empty?
     unless resource[:ensure] == :absent
        flush_instance_of('affinity', name, @property_hash[:object], build_params)
      end
    end
  end

  def destroy
    Puppet.info("Deleting kubernetes_affinity #{name}")
    destroy_instance_of('affinity', name)
    @property_hash[:ensure] = :absent
  end

  private
  def self.list_instances
    list_instances_of('affinity')
  end

  def build_params
    params = {
    
      
        nodeAffinity: resource[:node_affinity],
      
    
      
        podAffinity: resource[:pod_affinity],
      
    
      
        podAntiAffinity: resource[:pod_anti_affinity],
      
    
    }
    params.delete_if { |key, value| value.nil? }
    params
  end
end
