
# This file is automatically generated by puppet-swagger-generator and
# any manual changes are likely to be clobbered when the files
# are regenerated.

require_relative '../../../puppet_x/puppetlabs/kubernetes/provider'

Puppet::Type.type(:kubernetes_service_account).provide(:swagger, :parent => PuppetX::Puppetlabs::Kubernetes::Provider) do

  mk_resource_methods

  def self.instance_to_hash(instance)
    {
    ensure: :present,
    name: instance.metadata.name,
    
      
    
      
    
      
        metadata: instance.metadata.respond_to?(:to_hash) ? instance.metadata.to_hash : instance.metadata,
      
    
      
        secrets: instance.secrets.respond_to?(:to_hash) ? instance.secrets.to_hash : instance.secrets,
      
    
      
        image_pull_secrets: instance.imagePullSecrets.respond_to?(:to_hash) ? instance.imagePullSecrets.to_hash : instance.imagePullSecrets,
      
    
      
        automount_service_account_token: instance.automountServiceAccountToken.respond_to?(:to_hash) ? instance.automountServiceAccountToken.to_hash : instance.automountServiceAccountToken,
      
    
    object: instance,
    }
  end

  def create
    Puppet.info("Creating kubernetes_service_account #{name}")
    create_instance_of('service_account', name, build_params)
  end

  def flush
   unless @property_hash.empty?
     unless resource[:ensure] == :absent
        flush_instance_of('service_account', name, @property_hash[:object], build_params)
      end
    end
  end

  def destroy
    Puppet.info("Deleting kubernetes_service_account #{name}")
    destroy_instance_of('service_account', name)
    @property_hash[:ensure] = :absent
  end

  private
  def self.list_instances
    list_instances_of('service_account')
  end

  def build_params
    params = {
    
      
    
      
    
      
        metadata: resource[:metadata],
      
    
      
        secrets: resource[:secrets],
      
    
      
        imagePullSecrets: resource[:image_pull_secrets],
      
    
      
        automountServiceAccountToken: resource[:automount_service_account_token],
      
    
    }
    params.delete_if { |key, value| value.nil? }
    params
  end
end
