
# This file is automatically generated by puppet-swagger-generator and
# any manual changes are likely to be clobbered when the files
# are regenerated.

require_relative '../../puppet_x/puppetlabs/swagger/fuzzy_compare'

Puppet::Type.newtype(:kubernetes_volume_projection) do
  
  @doc = "Projection that may be projected along with other supported volume types"
  

  ensurable

  

  newparam(:name, namevar: true) do
    desc 'Name of the volume_projection.'
  end
  
    
      
      newproperty(:secret) do
      
        
        desc "information about the secret data to project"
        
        def insync?(is)
          PuppetX::Puppetlabs::Swagger::Utils::fuzzy_compare(is, should)
        end
      end
    
  
    
      
      newproperty(:downward_api) do
      
        
        desc "information about the downwardAPI data to project"
        
        def insync?(is)
          PuppetX::Puppetlabs::Swagger::Utils::fuzzy_compare(is, should)
        end
      end
    
  
    
      
      newproperty(:config_map) do
      
        
        desc "information about the configMap data to project"
        
        def insync?(is)
          PuppetX::Puppetlabs::Swagger::Utils::fuzzy_compare(is, should)
        end
      end
    
  
end
