
# This file is automatically generated by puppet-swagger-generator and
# any manual changes are likely to be clobbered when the files
# are regenerated.

require_relative '../../puppet_x/puppetlabs/swagger/fuzzy_compare'

Puppet::Type.newtype(:kubernetes_run_as_user_strategy_options) do
  
  @doc = "Run A sUser Strategy Options defines the strategy type and any options used to create the strategy."
  

  ensurable

  
  validate do
    required_properties = [
    
      :rule,
    
    ]
    required_properties.each do |property|
      # We check for both places so as to cover the puppet resource path as well
      if self[property].nil? and self.provider.send(property) == :absent
        fail "You must provide a #{property}"
      end
    end
  end
  

  newparam(:name, namevar: true) do
    desc 'Name of the run_as_user_strategy_options.'
  end
  
    
      
      newproperty(:rule) do
      
        
        desc "Rule is the strategy that will dictate the allowable RunAsUser values that may be set."
        
        def insync?(is)
          PuppetX::Puppetlabs::Swagger::Utils::fuzzy_compare(is, should)
        end
      end
    
  
    
      
      newproperty(:ranges, :array_matching => :all) do
      
        
        desc "Ranges are the allowed ranges of uids that may be used."
        
        def insync?(is)
          PuppetX::Puppetlabs::Swagger::Utils::fuzzy_compare(is, should)
        end
      end
    
  
end
