# This file is automatically generated by puppet-swagger-generator and
# any manual changes are likely to be clobbered when the files
# are regenerated.

require_relative '../../puppet_x/puppetlabs/swagger/fuzzy_compare'


Puppet::Type.newtype(:kubernetes_local_object_reference) do
  
  @doc = "LocalObjectReference contains enough information to let you locate the referenced object inside the same namespace."
  

  ensurable

  

  newparam(:name, namevar: true) do
    desc 'Name of the local_object_reference.'
  end
  
    
      newproperty(:name) do
        desc "Name of the referent. More info: http://releases.k8s.io/release-1.2/docs/user-guide/identifiers.md#names"
        def insync?(is)
          PuppetX::Puppetlabs::Swagger::Utils::fuzzy_compare(is, should)
        end
      end
    
  
end
