
# This file is automatically generated by puppet-swagger-generator and
# any manual changes are likely to be clobbered when the files
# are regenerated.

require_relative '../../puppet_x/puppetlabs/swagger/fuzzy_compare'

Puppet::Type.newtype(:kubernetes_secret_reference) do
  
  @doc = "SecretReference represents a Secret Reference. It has enough information to retrieve secret in any namespace"
  

  ensurable

  

  newparam(:name, namevar: true) do
    desc 'Name of the secret_reference.'
  end
  
    
      newproperty(:name) do
        
        desc "Name is unique within a namespace to reference a secret resource."
        
        def insync?(is)
          PuppetX::Puppetlabs::Swagger::Utils::fuzzy_compare(is, should)
        end
      end
    
  
    
      newproperty(:namespace) do
        
        desc "Namespace defines the space within which the secret name must be unique."
        
        def insync?(is)
          PuppetX::Puppetlabs::Swagger::Utils::fuzzy_compare(is, should)
        end
      end
    
  
end
