# This file is automatically generated by puppet-swagger-generator and
# any manual changes are likely to be clobbered when the files
# are regenerated.

require_relative '../../puppet_x/puppetlabs/swagger/fuzzy_compare'


Puppet::Type.newtype(:kubernetes_empty_dir_volume_source) do
  
  @doc = "EmptyDirVolumeSource is temporary directory that shares a pod's lifetime."
  

  ensurable

  

  newparam(:name, namevar: true) do
    desc 'Name of the empty_dir_volume_source.'
  end
  
    
      newproperty(:medium) do
        desc "What type of storage medium should back this directory. The default is '' which means to use the node's default medium. Must be an empty string (default) or Memory. More info: http://releases.k8s.io/HEAD/docs/user-guide/volumes.md#emptydir"
        def insync?(is)
          PuppetX::Puppetlabs::Swagger::Utils::fuzzy_compare(is, should)
        end
      end
    
  
end
