# This file is automatically generated by puppet-swagger-generator and
# any manual changes are likely to be clobbered when the files
# are regenerated.

require_relative '../../puppet_x/puppetlabs/swagger/fuzzy_compare'


Puppet::Type.newtype(:kubernetes_se_linux_options) do
  
  @doc = "SELinuxOptions are the labels to be applied to the container"
  

  ensurable

  

  newparam(:name, namevar: true) do
    desc 'Name of the se_linux_options.'
  end
  
    
      newproperty(:user) do
        desc "User is a SELinux user label that applies to the container."
        def insync?(is)
          PuppetX::Puppetlabs::Swagger::Utils::fuzzy_compare(is, should)
        end
      end
    
  
    
      newproperty(:role) do
        desc "Role is a SELinux role label that applies to the container."
        def insync?(is)
          PuppetX::Puppetlabs::Swagger::Utils::fuzzy_compare(is, should)
        end
      end
    
  
    
      newproperty(:type) do
        desc "Type is a SELinux type label that applies to the container."
        def insync?(is)
          PuppetX::Puppetlabs::Swagger::Utils::fuzzy_compare(is, should)
        end
      end
    
  
    
      newproperty(:level) do
        desc "Level is SELinux level label that applies to the container."
        def insync?(is)
          PuppetX::Puppetlabs::Swagger::Utils::fuzzy_compare(is, should)
        end
      end
    
  
end
