
# This file is automatically generated by puppet-swagger-generator and
# any manual changes are likely to be clobbered when the files
# are regenerated.

require_relative '../../puppet_x/puppetlabs/swagger/fuzzy_compare'

Puppet::Type.newtype(:kubernetes_supplemental_groups_strategy_options) do
  
  @doc = "SupplementalGroupsStrategyOptions defines the strategy type and options used to create the strategy."
  

  ensurable

  

  newparam(:name, namevar: true) do
    desc 'Name of the supplemental_groups_strategy_options.'
  end
  
    
      
      newproperty(:rule) do
      
        
        desc "Rule is the strategy that will dictate what supplemental groups is used in the SecurityContext."
        
        def insync?(is)
          PuppetX::Puppetlabs::Swagger::Utils::fuzzy_compare(is, should)
        end
      end
    
  
    
      
      newproperty(:ranges, :array_matching => :all) do
      
        
        desc "Ranges are the allowed ranges of supplemental groups.  If you would like to force a single supplemental group then supply a single range with the same start and end."
        
        def insync?(is)
          PuppetX::Puppetlabs::Swagger::Utils::fuzzy_compare(is, should)
        end
      end
    
  
end
