# This file is automatically generated by puppet-swagger-generator and
# any manual changes are likely to be clobbered when the files
# are regenerated.

require 'puppet_x/puppetlabs/swagger/fuzzy_compare'


Puppet::Type.newtype(:kubernetes_finalizer_name) do
  

  ensurable

  

  newparam(:name, namevar: true) do
    desc 'Name of the finalizer_name.'
  end
  
end
