# This file is automatically generated by puppet-swagger-generator and
# any manual changes are likely to be clobbered when the files
# are regenerated.

require 'puppet_x/puppetlabs/swagger/fuzzy_compare'


Puppet::Type.newtype(:kubernetes_env_var_source) do
  
  @doc = "EnvVarSource represents a source for the value of an EnvVar."
  

  ensurable

  
  validate do
    required_properties = [
    
      fieldRef,
    
    ]
    required_properties.each do |property|
      # We check for both places so as to cover the puppet resource path as well
      if self[property].nil? and self.provider.send(property) == :absent
        fail "You must provide a #{property}"
      end
    end
  end
  

  newparam(:name, namevar: true) do
    desc 'Name of the env_var_source.'
  end
  
    
      newproperty(:fieldRef) do
        desc "Selects a field of the pod. Only name and namespace are supported."
        def insync?(is)
          PuppetX::Puppetlabs::Swagger::Utils::fuzzy_compare(is, should)
        end
      end
    
  
end
