
# This file is automatically generated by puppet-swagger-generator and
# any manual changes are likely to be clobbered when the files
# are regenerated.

require_relative '../../puppet_x/puppetlabs/swagger/fuzzy_compare'

Puppet::Type.newtype(:kubernetes_host_port_range) do
  
  @doc = "Host Port Range defines a range of host ports that will be enabled by a policy for pods to use.  It requires both the start and end to be defined."
  

  ensurable

  
  validate do
    required_properties = [
    
      :min,
    
      :max,
    
    ]
    required_properties.each do |property|
      # We check for both places so as to cover the puppet resource path as well
      if self[property].nil? and self.provider.send(property) == :absent
        fail "You must provide a #{property}"
      end
    end
  end
  

  newparam(:name, namevar: true) do
    desc 'Name of the host_port_range.'
  end
  
    
      newproperty(:min) do
        
        desc "min is the start of the range, inclusive."
        
        def insync?(is)
          PuppetX::Puppetlabs::Swagger::Utils::fuzzy_compare(is, should)
        end
      end
    
  
    
      newproperty(:max) do
        
        desc "max is the end of the range, inclusive."
        
        def insync?(is)
          PuppetX::Puppetlabs::Swagger::Utils::fuzzy_compare(is, should)
        end
      end
    
  
end
