
# This file is automatically generated by puppet-swagger-generator and
# any manual changes are likely to be clobbered when the files
# are regenerated.

require_relative '../../puppet_x/puppetlabs/swagger/fuzzy_compare'

Puppet::Type.newtype(:kubernetes_eviction) do
  
  @doc = "Eviction evicts a pod from its node subject to certain policies and safety constraints. This is a subresource of Pod.  A request to cause such an eviction is created by POSTing to .../pods/<pod name>/evictions."
  

  ensurable

  

  newparam(:name, namevar: true) do
    desc 'Name of the eviction.'
  end
  
    
  
    
  
    
      
      newproperty(:metadata) do
      
        
        desc "ObjectMeta describes the pod that is being evicted."
        
        def insync?(is)
          PuppetX::Puppetlabs::Swagger::Utils::fuzzy_compare(is, should)
        end
      end
    
  
    
      
      newproperty(:delete_options) do
      
        
        desc "DeleteOptions may be provided"
        
        def insync?(is)
          PuppetX::Puppetlabs::Swagger::Utils::fuzzy_compare(is, should)
        end
      end
    
  
end
