# This file is automatically generated by puppet-swagger-generator and
# any manual changes are likely to be clobbered when the files
# are regenerated.

require_relative '../../../puppet_x/puppetlabs/kubernetes/provider'

Puppet::Type.type(:kubernetes_probe).provide(:swagger, :parent => PuppetX::Puppetlabs::Kubernetes::Provider) do

  mk_resource_methods

  def self.instance_to_hash(instance)
    {
    ensure: :present,
    name: instance.metadata.name,
    
      
        exec: instance.exec.respond_to?(:to_hash) ? instance.exec.to_hash : instance.exec,
      
    
      
        httpGet: instance.httpGet.respond_to?(:to_hash) ? instance.httpGet.to_hash : instance.httpGet,
      
    
      
        tcpSocket: instance.tcpSocket.respond_to?(:to_hash) ? instance.tcpSocket.to_hash : instance.tcpSocket,
      
    
      
        initialDelaySeconds: instance.initialDelaySeconds.respond_to?(:to_hash) ? instance.initialDelaySeconds.to_hash : instance.initialDelaySeconds,
      
    
      
        timeoutSeconds: instance.timeoutSeconds.respond_to?(:to_hash) ? instance.timeoutSeconds.to_hash : instance.timeoutSeconds,
      
    
      
        periodSeconds: instance.periodSeconds.respond_to?(:to_hash) ? instance.periodSeconds.to_hash : instance.periodSeconds,
      
    
      
        successThreshold: instance.successThreshold.respond_to?(:to_hash) ? instance.successThreshold.to_hash : instance.successThreshold,
      
    
      
        failureThreshold: instance.failureThreshold.respond_to?(:to_hash) ? instance.failureThreshold.to_hash : instance.failureThreshold,
      
    
    object: instance,
    }
  end

  def create
    Puppet.info("Creating kubernetes_probe #{name}")
    create_instance_of('probe', name, build_params)
  end

  def flush
   unless @property_hash.empty?
     unless resource[:ensure] == :absent
        flush_instance_of('probe', name, @property_hash[:object], build_params)
      end
    end
  end

  def destroy
    Puppet.info("Deleting kubernetes_probe #{name}")
    destroy_instance_of('probe', name)
    @property_hash[:ensure] = :absent
  end

  private
  def self.list_instances
    list_instances_of('probe')
  end

  def build_params
    params = {
    
      
        exec: resource[:exec],
      
    
      
        httpGet: resource[:httpGet],
      
    
      
        tcpSocket: resource[:tcpSocket],
      
    
      
        initialDelaySeconds: resource[:initialDelaySeconds],
      
    
      
        timeoutSeconds: resource[:timeoutSeconds],
      
    
      
        periodSeconds: resource[:periodSeconds],
      
    
      
        successThreshold: resource[:successThreshold],
      
    
      
        failureThreshold: resource[:failureThreshold],
      
    
    }
    params.delete_if { |key, value| value.nil? }
    params
  end
end
