# This file is automatically generated by puppet-swagger-generator and
# any manual changes are likely to be clobbered when the files
# are regenerated.

require 'puppet_x/puppetlabs/swagger/prefetch_error'
require 'puppet_x/puppetlabs/swagger/symbolize_keys'
require 'puppet_x/puppetlabs/kubernetes/provider'

Puppet::Type.type(:kubernetes_namespace_spec).provide(:swagger, :parent => PuppetX::Puppetlabs::Kubernetes::Provider) do

  mk_resource_methods

  def self.instance_to_hash(instance)
    {
    ensure: :present,
    name: instance.metadata.name,
    
      
        finalizers: instance.finalizers.respond_to?(:to_hash) ? instance.finalizers.to_hash : instance.finalizers,
      
    
    object: instance,
    }
  end

  def create
    Puppet.info("Creating kubernetes_namespace_spec #{name}")
    create_instance_of('namespace_spec', name, build_params)
  end

  def flush
    if ! @property_hash.empty? and @property_hash[:ensure] != :absent
      flush_instance_of('namespace_spec', name, @property_hash[:object], build_params)
    end
  end

  def destroy
    Puppet.info("Deleting kubernetes_namespace_spec #{name}")
    destroy_instance_of('namespace_spec', name)
  end

  private
  def self.list_instances
    list_instances_of('namespace_spec')
  end

  def build_params
    params = {
    
      
        finalizers: resource[:finalizers],
      
    
    }
    params.delete_if { |key, value| value.nil? }
    params
  end
end
